openapi: 3.0.3
info:
  version: '3.0'
  title: Fyle REST API
  contact:
    name: Integrations
    email: support@fyle.in
servers:
  - url: 'https://accounts.fylehq.com'
    description: Live Server

components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://accounts.fylehq.com/app/developers/#/oauth/authorize'
          tokenUrl: 'https://accounts.fylehq.com/oauth/token'
          scopes:
            admin.*: Grant all ADMIN actions

tags:
  - name: Employees
    description: |
      These APIs gives you access to manage your organisation's Employees data.
  - name: Expenses
    description: |
      This API gives you access to your organisation's Expenses data.
  - name: Expense Custom Properties
    description: |
      This API gives you access to your organisation's Expenses Custom Properties data.
  - name: Reports
    description: |
      This API gives you access to your organisation's Expense Reports data.
  - name: Advances
    description: |
      This API gives you access to Issued Advances data of your organisation.
  - name: Advance Requests
    description: |
      This API gives you access to your organisation's Advance requests data.
  - name: Reimbursements
    description: |
      These APIs gives you access to manage your organisation's Reimbursements data.
  - name: Projects
    description: |
      These APIs gives you access to manage your organisation's Projects data.
  - name: Cost Centers
    description: |
      These APIs gives you access to manage your organisation's Cost Centers data.
  - name: Refunds
    description: |
      These APIs gives you access to manage your organisation's Refunds data.
  - name: Settlements
    description: |
      These APIs gives you access to manage your organisation's Settlements data.
  - name: Balance Transfers
    description: |
      These APIs gives you access to manage your organisation's balance transfers data.
  - name: Orgs
    description: |
      This API gives you access to your current org data.

paths:
  /v4/admin/employees:
    $ref: 'paths/employees.yaml'
  /v4/admin/expenses:
    $ref: 'paths/expenses.yaml'
  /v4/admin/expense_custom_properties:
    $ref: 'paths/expense_custom_properties.yaml'
  /v4/admin/reports:
    $ref: 'paths/reports.yaml'
  /v4/admin/advance_requests:
    $ref: 'paths/advance_requests.yaml'
  /v4/admin/advances:
    $ref: 'paths/advances.yaml'
  /v4/admin/reimbursements:
    $ref: 'paths/reimbursements.yaml'
  /v4/admin/refunds:
    $ref: 'paths/refunds.yaml'
  /v4/admin/settlements:
    $ref: 'paths/settlements.yaml'
  /v4/admin/balance_transfers:
    $ref: 'paths/balance_transfers.yaml'
  /v4/admin/projects:
    $ref: 'paths/projects.yaml'
  /v4/admin/cost_centers:
    $ref: 'paths/cost_centers.yaml'