openapi: 3.0.3
info:
  version: '3.0'
  title: Fyle REST API
  contact:
    name: Integrations
    email: support@fyle.in
servers:
  - url: 'https://accounts.fylehq.com'
    description: Live Server

components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://accounts.fylehq.com/app/developers/#/oauth/authorize'
          tokenUrl: 'https://accounts.fylehq.com/oauth/token'
          scopes:
            admin.*: Grant all ADMIN actions

tags:
  - name: Employees
    description: |
      These APIs gives you access to manage your Employees data.
  - name: Reimbursements
    description: |
      These APIs gives you access to fetch your Reimbursements data.
  - name: Cost Centers
    description: |
      These APIs gives you access to manage your Cost Centers data.
  - name: Refunds
    description: |
      These APIs gives you access to manage your Refunds data.
  - name: Settlements
    description: |
      These APIs gives you access to manage your Settlements data.
  - name: Balance Transfers
    description: |
      These APIs gives you access to manage your balance transfers data.
  - name: Orgs
    description: |
      This API gives you access to your current org data.

paths:
  /v4/admin/employees:
    $ref: 'paths/employees.yaml'
  /v4/admin/cost_centers:
      $ref: 'paths/cost_centers.yaml'
  /v4/admin/reimbursements:
    $ref: 'paths/reimbursements.yaml'
  /v4/admin/refunds:
    $ref: 'paths/refunds.yaml'
  /v4/admin/settlements:
    $ref: 'paths/settlements.yaml'
  /v4/admin/orgs:
    $ref: 'paths/orgs.yaml'
  /v4/admin/balance_transfers:
    $ref: 'paths/balance_transfers.yaml'